# Generated by Django 5.1.3 on 2024-11-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='계급',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('계급', models.CharField(max_length=50)),
                ('채팅', models.IntegerField()),
                ('보상률', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '계급',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='유저',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('텔레그램ID', models.CharField(max_length=50)),
                ('이름', models.CharField(max_length=50)),
                ('이번주_채팅', models.IntegerField(default=0)),
                ('채팅', models.IntegerField(default=0)),
                ('오늘출석', models.BooleanField(default=False)),
                ('TRX', models.IntegerField(default=0)),
                ('reward_threshold', models.IntegerField(default=0)),
                ('계급', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CoinGryComm.계급')),
            ],
            options={
                'verbose_name_plural': '유저',
                'ordering': ['-id'],
            },
        ),
    ]
