# Generated by Django 5.1.3 on 2024-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mvp_타이머',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('요일', models.CharField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')], max_length=8)),
                ('시', models.IntegerField()),
                ('분', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MVP 타이머',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='유저',
            name='TRX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='유저',
            name='reward_threshold',
            field=models.IntegerField(default=3),
        ),
    ]
