# Generated by Django 5.1.3 on 2024-11-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0002_mvp_타이머_alter_유저_trx_alter_유저_reward_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvp_타이머',
            name='요일',
            field=models.IntegerField(choices=[(0, '월요일'), (1, '화요일'), (2, '수요일'), (3, '목요일'), (4, '금요일'), (5, '토요일'), (6, '일요일')]),
        ),
    ]
