# Generated by Django 5.1.3 on 2024-11-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0003_alter_mvp_타이머_요일'),
    ]

    operations = [
        migrations.CreateModel(
            name='가위바위보',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('텔레그램ID', models.CharField(max_length=50)),
                ('이름', models.CharField(max_length=50)),
                ('TRX입력', models.BooleanField(default=False)),
                ('TRX', models.IntegerField(blank=True, null=True)),
                ('선택', models.CharField(default='None', max_length=10)),
                ('생성일', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '가위바위보 실시간',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='가위바위보_타이머',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('매칭대기시간', models.IntegerField()),
                ('가위바위보_선택시간', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '가위바위보 타이머',
                'ordering': ['-id'],
            },
        ),
    ]
