# Generated by Django 5.1.3 on 2024-12-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0004_가위바위보_가위바위보_타이머'),
    ]

    operations = [
        migrations.AddField(
            model_name='유저',
            name='트레이딩게임_누적_승리',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='유저',
            name='트레이딩게임_누적_패배',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='유저',
            name='트레이딩게임_연승',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='유저',
            name='트레이딩게임_총수익',
            field=models.IntegerField(default=0),
        ),
    ]
