# Generated by Django 5.1.3 on 2024-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0005_유저_트레이딩게임_누적_승리_유저_트레이딩게임_누적_패배_유저_트레이딩게임_연승_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='트레이딩게임',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('캔들', models.CharField(choices=[('15분', '15분'), ('30분', '30분'), ('1시간', '1시간')], max_length=10)),
                ('시가', models.FloatField()),
                ('종가', models.FloatField(blank=True, null=True)),
                ('방향', models.CharField(blank=True, max_length=10, null=True)),
                ('베팅중', models.BooleanField(default=True)),
                ('진행중', models.BooleanField(default=True)),
                ('생성일', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '트레이딩게임 실시간',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='트레이딩게임_베팅',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('게임ID', models.IntegerField()),
                ('텔레그램ID', models.CharField(max_length=50)),
                ('방향', models.CharField(default='미입력', max_length=10)),
                ('TRX', models.IntegerField(default=0)),
                ('생성일', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '트레이딩게임 베팅 기록',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='트레이딩게임_설정',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('캔들', models.CharField(choices=[('15분', '15분'), ('30분', '30분'), ('1시간', '1시간')], max_length=10)),
                ('베팅마감시간', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '트레이딩게임 설정',
                'ordering': ['-id'],
            },
        ),
    ]
