# Generated by Django 5.1.3 on 2024-12-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0006_트레이딩게임_트레이딩게임_베팅_트레이딩게임_설정'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='트레이딩게임_베팅',
            options={'ordering': ['-id'], 'verbose_name_plural': '트레이딩게임 기록'},
        ),
        migrations.AddField(
            model_name='트레이딩게임_설정',
            name='이미지',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
