# Generated by Django 5.1.3 on 2025-01-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0007_alter_트레이딩게임_베팅_options_트레이딩게임_설정_이미지'),
    ]

    operations = [
        migrations.CreateModel(
            name='공포_롱숏',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('공포', models.IntegerField()),
                ('롱숏', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '공포/롱숏',
                'ordering': ['-id'],
            },
        ),
    ]
