# Generated by Django 5.1.3 on 2025-06-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0008_공포_롱숏'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mvp_타이머',
        ),
        migrations.DeleteModel(
            name='공포_롱숏',
        ),
    ]
