# Generated by Django 5.1.3 on 2025-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0009_delete_mvp_타이머_delete_공포_롱숏'),
    ]

    operations = [
        migrations.AlterField(
            model_name='트레이딩게임',
            name='캔들',
            field=models.CharField(choices=[('5분', '5분'), ('15분', '15분'), ('30분', '30분'), ('1시간', '1시간')], max_length=10),
        ),
        migrations.AlterField(
            model_name='트레이딩게임_설정',
            name='캔들',
            field=models.CharField(choices=[('5분', '5분'), ('15분', '15분'), ('30분', '30분'), ('1시간', '1시간')], max_length=10),
        ),
    ]
