# Generated by Django 5.1.3 on 2025-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0010_alter_트레이딩게임_캔들_alter_트레이딩게임_설정_캔들'),
    ]

    operations = [
        migrations.AddField(
            model_name='트레이딩게임',
            name='차트_메시지_ID',
            field=models.IntegerField(blank=True, help_text='Telegram 차트 메시지 ID (실시간 업데이트용)', null=True),
        ),
    ]
