# Generated by Django 5.1.3 on 2026-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0011_add_chart_message_id_to_trading_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2POTCOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc_txid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('order_type', models.CharField(choices=[('buy', '구매'), ('sell', '판매')], db_index=True, max_length=4)),
                ('coin', models.CharField(db_index=True, max_length=20)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('adjust_type', models.CharField(default='+', max_length=2)),
                ('percentage', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('transfer', '이체거래'), ('face_to_face', '대면거래')], db_index=True, default='transfer', max_length=20)),
                ('posted_status', models.CharField(choices=[('출력되지않음', '출력되지않음'), ('출력됨', '출력됨')], db_index=True, default='출력되지않음', max_length=20)),
                ('matched_status', models.CharField(choices=[('매칭되지않음', '매칭되지않음'), ('매칭됨', '매칭됨')], db_index=True, default='매칭되지않음', max_length=20)),
                ('channel_message_id', models.BigIntegerField(blank=True, null=True)),
                ('creator_telegram_id', models.CharField(db_index=True, max_length=50)),
                ('creator_name', models.CharField(blank=True, default='', max_length=100)),
                ('creator_username', models.CharField(blank=True, default='', max_length=100)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matcher_telegram_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('matcher_name', models.CharField(blank=True, default='', max_length=100)),
                ('matcher_username', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'P2P/OTC 주문',
                'ordering': ['-created_at'],
            },
        ),
    ]
