# Generated by Django 5.1.3 on 2026-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0012_p2potcorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2potcorder',
            name='amount_range',
            field=models.CharField(blank=True, help_text='금액 범위 정보 (예: 100만 미만, 1000만 미만 등)', max_length=50, null=True),
        ),
    ]
