# Generated by Django 5.1.3 on 2026-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinGryComm', '0013_add_amount_range_to_p2potcorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2potcorder',
            name='quantity_range',
            field=models.CharField(blank=True, help_text='갯수 범위 정보 (예: 100개 미만, 1000개 미만 등)', max_length=50, null=True),
        ),
    ]
