# Generated by Django 5.1.3 on 2026-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CoinGryComm", "0014_add_quantity_range_to_p2potcorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="p2potcorder",
            name="order_source",
            field=models.CharField(
                choices=[("manual", "일반주문"), ("auto", "자동주문")],
                db_index=True,
                default="manual",
                help_text="주문 생성 경로 (저장 시점에 자동으로 분류)",
                max_length=10,
            ),
        ),
    ]

