# Generated by Django 5.1.3 on 2026-01-13 00:01

from django.db import migrations
from django.db.models import Q


AUTO_USER_IDS = [
    "5880880272",
    "5451514325",
    "6405671801",
    "6284744511",
    "6514545595",
]

AUTO_USERNAMES = [
    "COINGRY_official",
    "CoinGry_CS",
    "btcmagazine99",
    "Corini_R",
    "TetherBox_P2P",
    "dianaping",
]


def forward(apps, schema_editor):
    P2POTCOrder = apps.get_model("CoinGryComm", "P2POTCOrder")
    q = Q()
    if AUTO_USER_IDS:
        q |= Q(creator_telegram_id__in=AUTO_USER_IDS)
    if AUTO_USERNAMES:
        q |= Q(creator_username__in=AUTO_USERNAMES)
    if not q:
        return
    # 이미 값이 들어간 레코드는 건드리지 않음 (안전)
    P2POTCOrder.objects.filter(q, order_source="manual").update(order_source="auto")


def backward(apps, schema_editor):
    # 되돌림은 의도적으로 no-op (운영에서 수동 분류를 되돌릴 위험 방지)
    return


class Migration(migrations.Migration):

    dependencies = [
        ("CoinGryComm", "0015_add_order_source_to_p2potcorder"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]

