# Generated by Django 5.1.3 on 2026-01-27 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(choices=[('search_console', 'Search Console'), ('pagespeed', 'PageSpeed Insights'), ('lighthouse', 'Lighthouse'), ('analytics', 'Google Analytics')], max_length=50)),
                ('requests_made', models.IntegerField(default=0)),
                ('quota_limit', models.IntegerField(blank=True, null=True)),
                ('quota_remaining', models.IntegerField(blank=True, null=True)),
                ('rate_limit_hits', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'API Quota Usage',
                'db_table': 'seo_api_quota_usage',
                'ordering': ['-date'],
                'unique_together': {('api_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='https', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('next_scan_at', models.DateTimeField(blank=True, null=True)),
                ('search_console_connected', models.BooleanField(default=False)),
                ('analytics_connected', models.BooleanField(default=False)),
                ('avg_seo_score', models.FloatField(blank=True, null=True)),
                ('avg_performance_score', models.FloatField(blank=True, null=True)),
                ('avg_accessibility_score', models.FloatField(blank=True, null=True)),
                ('avg_pwa_score', models.FloatField(blank=True, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_subdomains', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'db_table': 'seo_domains',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500)),
                ('path', models.CharField(max_length=500)),
                ('is_subdomain', models.BooleanField(default=False)),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True)),
                ('depth_level', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('404', 'Not Found'), ('500', 'Server Error'), ('redirected', 'Redirected')], default='active', max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='seo_analyzer.domain')),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='seo_analyzer.page')),
            ],
            options={
                'db_table': 'seo_pages',
                'ordering': ['depth_level', 'url'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('accessibility_score', models.FloatField(blank=True, null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('total_clicks', models.BigIntegerField(blank=True, null=True)),
                ('total_impressions', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_metrics', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'Historical Metrics',
                'db_table': 'seo_historical_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.BigIntegerField(blank=True, null=True)),
                ('unique_visitors', models.BigIntegerField(blank=True, null=True)),
                ('sessions', models.BigIntegerField(blank=True, null=True)),
                ('avg_session_duration', models.FloatField(blank=True, help_text='Seconds', null=True)),
                ('bounce_rate', models.FloatField(blank=True, help_text='Percentage', null=True)),
                ('pages_per_session', models.FloatField(blank=True, null=True)),
                ('new_users', models.BigIntegerField(blank=True, null=True)),
                ('returning_users', models.BigIntegerField(blank=True, null=True)),
                ('goal_completions', models.BigIntegerField(blank=True, null=True)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('organic_traffic', models.BigIntegerField(blank=True, null=True)),
                ('direct_traffic', models.BigIntegerField(blank=True, null=True)),
                ('referral_traffic', models.BigIntegerField(blank=True, null=True)),
                ('social_traffic', models.BigIntegerField(blank=True, null=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'Analytics Data',
                'db_table': 'seo_analytics_data',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full_scan', 'Full Scan'), ('quick_refresh', 'Quick Refresh'), ('subdomain_discovery', 'Subdomain Discovery')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('pages_scanned', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'Scan Jobs',
                'db_table': 'seo_scan_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('accessibility_score', models.FloatField(blank=True, null=True)),
                ('best_practices_score', models.FloatField(blank=True, null=True)),
                ('pwa_score', models.FloatField(blank=True, null=True)),
                ('lcp', models.FloatField(blank=True, help_text='Largest Contentful Paint (ms)', null=True)),
                ('fid', models.FloatField(blank=True, help_text='First Input Delay (ms)', null=True)),
                ('cls', models.FloatField(blank=True, help_text='Cumulative Layout Shift', null=True)),
                ('fcp', models.FloatField(blank=True, help_text='First Contentful Paint (ms)', null=True)),
                ('tti', models.FloatField(blank=True, help_text='Time to Interactive (ms)', null=True)),
                ('tbt', models.FloatField(blank=True, help_text='Total Blocking Time (ms)', null=True)),
                ('impressions', models.BigIntegerField(blank=True, null=True)),
                ('clicks', models.BigIntegerField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, help_text='Click-through rate', null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('index_status', models.CharField(blank=True, max_length=100, null=True)),
                ('coverage_state', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_friendly', models.BooleanField(default=False)),
                ('mobile_score', models.FloatField(blank=True, null=True)),
                ('desktop_score', models.FloatField(blank=True, null=True)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_metrics', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'SEO Metrics',
                'db_table': 'seo_metrics',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['domain', 'is_subdomain'], name='seo_pages_domain__b86763_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['domain', 'status'], name='seo_pages_domain__26a680_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('domain', 'url')},
        ),
        migrations.AddIndex(
            model_name='historicalmetrics',
            index=models.Index(fields=['page', '-date'], name='seo_histori_page_id_8eb89e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalmetrics',
            unique_together={('page', 'date')},
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['page', '-snapshot_date'], name='seo_analyti_page_id_3cfd95_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['date_from', 'date_to'], name='seo_analyti_date_fr_791d06_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['domain', '-created_at'], name='seo_scan_jo_domain__cc0fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', '-created_at'], name='seo_scan_jo_status_677784_idx'),
        ),
        migrations.AddIndex(
            model_name='seometrics',
            index=models.Index(fields=['page', '-snapshot_date'], name='seo_metrics_page_id_4bf454_idx'),
        ),
    ]
