# Generated by Django 5.1.3 on 2026-01-28 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_label',
            field=models.CharField(blank=True, help_text='Custom display label (overrides auto-generated label)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='is_collapsed',
            field=models.BooleanField(default=False, help_text='Collapse subtree in tree visualization'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show or hide node in tree visualization'),
        ),
        migrations.AddField(
            model_name='page',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last manually edited this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='last_manually_edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manual customizations were last made', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='manual_position_x',
            field=models.FloatField(blank=True, help_text='Custom X position in tree visualization', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='manual_position_y',
            field=models.FloatField(blank=True, help_text='Custom Y position in tree visualization', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='use_manual_position',
            field=models.BooleanField(default=False, help_text='Use manual position instead of auto-calculated layout'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['domain', 'use_manual_position'], name='seo_pages_domain__82cc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_visible'], name='seo_pages_is_visi_14a12b_idx'),
        ),
    ]
