# Generated by Django 5.1.3 on 2026-01-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0002_page_custom_label_page_is_collapsed_page_is_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_groups', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'Page Groups',
                'db_table': 'seo_page_groups',
                'ordering': ['domain', 'name'],
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group for organizing pages', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='seo_analyzer.pagegroup'),
        ),
    ]
