# Generated by Django 5.1.3 on 2026-01-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0003_pagegroup_page_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagegroup',
            options={'ordering': ['domain', 'category__order', 'order', 'name'], 'verbose_name_plural': 'Page Groups'},
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within category'),
        ),
        migrations.CreateModel(
            name='PageGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='📁', help_text='Emoji or icon name', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_expanded', models.BooleanField(default=True, help_text='UI expansion state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_categories', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'Page Group Categories',
                'db_table': 'seo_page_group_categories',
                'ordering': ['domain', 'order', 'name'],
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional category for organizing groups', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='seo_analyzer.pagegroupcategory'),
        ),
    ]
