# Generated by Django 5.1.3 on 2026-01-30 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0018_fix_icon_charset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_images', models.BooleanField(default=True)),
                ('include_videos', models.BooleanField(default=False)),
                ('max_urls', models.IntegerField(default=50000)),
                ('deployment_method', models.CharField(choices=[('direct', 'Direct (Django Static)'), ('ftp', 'FTP'), ('sftp', 'SFTP'), ('git', 'Git')], default='direct', max_length=20)),
                ('deployment_config', models.JSONField(blank=True, default=dict)),
                ('auto_generate', models.BooleanField(default=True)),
                ('auto_deploy', models.BooleanField(default=False)),
                ('auto_submit_to_search_console', models.BooleanField(default=False)),
                ('existing_sitemap_url', models.URLField(blank=True, help_text='URL of existing sitemap to import', max_length=500, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_config', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'Sitemap Configs',
                'db_table': 'seo_sitemap_configs',
            },
        ),
        migrations.CreateModel(
            name='SitemapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_count', models.IntegerField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('sitemap_url', models.URLField(blank=True, max_length=500, null=True)),
                ('generated', models.BooleanField(default=False)),
                ('deployed', models.BooleanField(default=False)),
                ('submitted_to_search_console', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_history', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'Sitemap History',
                'db_table': 'seo_sitemap_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('page', 'Page Analysis'), ('domain', 'Domain Analysis')], max_length=20)),
                ('overall_health_score', models.IntegerField(default=0)),
                ('critical_issues_count', models.IntegerField(default=0)),
                ('warning_issues_count', models.IntegerField(default=0)),
                ('info_issues_count', models.IntegerField(default=0)),
                ('auto_fixable_count', models.IntegerField(default=0)),
                ('fixed_count', models.IntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('action_plan', models.JSONField(blank=True, default=dict)),
                ('auto_fix_results', models.JSONField(blank=True, default=dict)),
                ('potential_score_gain', models.IntegerField(default=0)),
                ('estimated_fix_time_minutes', models.IntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_reports', to='seo_analyzer.domain')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_reports', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'SEO Analysis Reports',
                'db_table': 'seo_analysis_reports',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['domain', 'report_type', '-analyzed_at'], name='seo_analysi_domain__c93756_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEOIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ignored', 'Ignored'), ('auto_fixed', 'Auto Fixed')], db_index=True, default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('fix_suggestion', models.TextField(blank=True, null=True)),
                ('auto_fix_available', models.BooleanField(default=False)),
                ('auto_fix_method', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.CharField(default='medium', max_length=20)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('suggested_value', models.TextField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_issues', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'SEO Issues',
                'db_table': 'seo_issues',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['page', 'status'], name='seo_issues_page_id_f9d68c_idx'), models.Index(fields=['severity', 'status'], name='seo_issues_severit_ac72e7_idx'), models.Index(fields=['detected_at'], name='seo_issues_detecte_3f6812_idx')],
            },
        ),
    ]
