# Generated by Django 5.1.3 on 2026-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0019_sitemapconfig_sitemaphistory_seoanalysisreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='git_enabled',
            field=models.BooleanField(default=False, help_text='Enable Git auto-deployment for SEO fixes'),
        ),
        migrations.AddField(
            model_name='domain',
            name='git_repository',
            field=models.CharField(max_length=500, null=True, blank=True, help_text='Git repository URL (e.g., https://github.com/user/repo.git)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='git_branch',
            field=models.CharField(max_length=100, default='main', help_text='Git branch to push to'),
        ),
        migrations.AddField(
            model_name='domain',
            name='git_token',
            field=models.CharField(max_length=500, null=True, blank=True, help_text='Git personal access token (encrypted)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='git_target_path',
            field=models.CharField(max_length=500, default='public', help_text='Path in repo where HTML files are located (e.g., public, dist)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='vercel_project_id',
            field=models.CharField(max_length=200, null=True, blank=True, help_text='Vercel project ID (optional)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='vercel_token',
            field=models.CharField(max_length=500, null=True, blank=True, help_text='Vercel API token (optional, for deployment tracking)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_deployed_at',
            field=models.DateTimeField(null=True, blank=True, help_text='Last Git push timestamp'),
        ),
        migrations.AddField(
            model_name='domain',
            name='deployment_status',
            field=models.CharField(max_length=50, default='never', help_text='Deployment status: never, pending, success, failed'),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_deployment_error',
            field=models.TextField(null=True, blank=True, help_text='Last deployment error message'),
        ),
    ]
