# Generated by Django 5.1.3 on 2026-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0020_add_git_vercel_deployment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoissue',
            name='deployed_at',
            field=models.DateTimeField(blank=True, help_text='When the fix was deployed to Git', null=True),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='deployed_to_git',
            field=models.BooleanField(default=False, help_text='Whether the fix was deployed to Git'),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='deployment_commit_hash',
            field=models.CharField(blank=True, help_text='Git commit hash of deployment', max_length=40, null=True),
        ),
    ]
