# Generated by Django 5.1.3 on 2026-01-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0021_seoissue_deployed_at_seoissue_deployed_to_git_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoissue',
            name='verification_status',
            field=models.CharField(choices=[('not_deployed', 'Not Deployed'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('needs_attention', 'Needs Attention')], default='not_deployed', help_text='Verification status after Git deployment', max_length=20),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the fix was verified', null=True),
        ),
    ]
