# Generated by Django 5.1.3 on 2026-02-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0022_add_verification_status_to_seoissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometrics',
            name='top_queries',
            field=models.JSONField(blank=True, help_text='Top search queries for this page from Search Console', null=True),
        ),
    ]
