# Generated by Django 5.1.3 on 2026-02-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0023_add_top_queries_to_seometrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='has_sitemap_mismatch',
            field=models.BooleanField(db_index=True, default=False, help_text='True if sitemap URL differs from canonical URL (redirect issue)'),
        ),
        migrations.AddField(
            model_name='page',
            name='redirect_chain',
            field=models.JSONField(blank=True, help_text='List of redirect hops from sitemap URL to canonical URL', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='sitemap_url',
            field=models.URLField(blank=True, help_text='URL as it appears in the sitemap (may differ from canonical due to redirects)', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='seometrics',
            name='canonical_coverage_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seometrics',
            name='canonical_index_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seometrics',
            name='canonical_is_indexed',
            field=models.BooleanField(blank=True, help_text='Index status of canonical URL', null=True),
        ),
    ]
