# Generated by Django 5.1.3 on 2026-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0024_sitemap_mismatch_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sitemap_entry',
            field=models.JSONField(blank=True, help_text='Original sitemap entry data (loc, lastmod, changefreq, priority)', null=True),
        ),
    ]
