# Generated by Django 5.1.3 on 2026-02-01 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0025_add_sitemap_entry_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional session name', max_length=200, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preview', 'Preview'), ('validating', 'Validating'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('entries_added', models.IntegerField(default=0)),
                ('entries_removed', models.IntegerField(default=0)),
                ('entries_modified', models.IntegerField(default=0)),
                ('total_entries', models.IntegerField(default=0)),
                ('ai_issues_found', models.JSONField(blank=True, default=list, help_text='List of issues found by AI')),
                ('ai_suggestions', models.JSONField(blank=True, default=list, help_text='AI suggestions for improvements')),
                ('ai_analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('deployment_commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('deployment_message', models.TextField(blank=True, null=True)),
                ('deployment_error', models.TextField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('preview_xml', models.TextField(blank=True, help_text='Generated XML preview', null=True)),
                ('preview_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitemap_edit_sessions', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_edit_sessions', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'Sitemap Edit Sessions',
                'db_table': 'seo_sitemap_edit_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SitemapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.URLField(help_text='URL location', max_length=2048)),
                ('loc_hash', models.CharField(db_index=True, editable=False, help_text='SHA256 hash of loc for uniqueness constraint', max_length=64)),
                ('lastmod', models.DateField(blank=True, help_text='Last modification date', null=True)),
                ('changefreq', models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], help_text='Change frequency', max_length=20, null=True)),
                ('priority', models.DecimalField(blank=True, decimal_places=1, help_text='Priority (0.0-1.0)', max_digits=2, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_add', 'Pending Add'), ('pending_remove', 'Pending Remove'), ('pending_modify', 'Pending Modify')], db_index=True, default='active', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('ai_suggested', models.BooleanField(default=False, help_text='Entry suggested by AI')),
                ('ai_suggestion_reason', models.TextField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_entries', to='seo_analyzer.domain')),
                ('page', models.ForeignKey(blank=True, help_text='Linked page (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitemap_entries', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'Sitemap Entries',
                'db_table': 'seo_sitemap_entries',
                'ordering': ['domain', 'loc'],
            },
        ),
        migrations.CreateModel(
            name='SitemapEntryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('modify', 'Modify')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Edit'), ('ai_suggestion', 'AI Suggestion'), ('bulk_import', 'Bulk Import'), ('sync', 'Sync from Live')], default='manual', max_length=20)),
                ('url', models.URLField(max_length=2048)),
                ('old_values', models.JSONField(blank=True, help_text='Values before change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Values after change', null=True)),
                ('ai_reason', models.TextField(blank=True, help_text='Reason if AI suggested', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitemap_changes', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to='seo_analyzer.sitemapentry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='seo_analyzer.sitemapeditsession')),
            ],
            options={
                'verbose_name_plural': 'Sitemap Entry Changes',
                'db_table': 'seo_sitemap_entry_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('sitemap', 'Sitemap Analysis'), ('seo_issues', 'SEO Issues Analysis'), ('page_content', 'Page Content Analysis'), ('full_domain', 'Full Domain Analysis')], max_length=30)),
                ('context_hash', models.CharField(db_index=True, help_text='Hash of input context for cache lookup', max_length=64)),
                ('analysis_result', models.JSONField(help_text='AI analysis result')),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(default='claude-sonnet-4-20250514', max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('api_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(help_text='Cache expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_cache', to='seo_analyzer.domain')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_cache', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name_plural': 'AI Analysis Cache',
                'db_table': 'seo_ai_analysis_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'analysis_type', 'context_hash'], name='seo_ai_anal_domain__284c61_idx'), models.Index(fields=['expires_at'], name='seo_ai_anal_expires_eb1271_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sitemapeditsession',
            index=models.Index(fields=['domain', 'status'], name='seo_sitemap_domain__556af8_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapeditsession',
            index=models.Index(fields=['domain', '-created_at'], name='seo_sitemap_domain__c7f8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapentry',
            index=models.Index(fields=['domain', 'status'], name='seo_sitemap_domain__b12937_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapentry',
            index=models.Index(fields=['domain', 'is_valid'], name='seo_sitemap_domain__78169f_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapentry',
            index=models.Index(fields=['ai_suggested'], name='seo_sitemap_ai_sugg_49f37b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitemapentry',
            unique_together={('domain', 'loc_hash')},
        ),
        migrations.AddIndex(
            model_name='sitemapentrychange',
            index=models.Index(fields=['session', '-created_at'], name='seo_sitemap_session_8d3abf_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapentrychange',
            index=models.Index(fields=['entry', '-created_at'], name='seo_sitemap_entry_i_3c8e97_idx'),
        ),
        migrations.AddIndex(
            model_name='sitemapentrychange',
            index=models.Index(fields=['change_type'], name='seo_sitemap_change__042bbb_idx'),
        ),
    ]
