# Generated by Django 5.1.3 on 2026-02-01 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0026_sitemap_editor_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('conversation_type', models.CharField(choices=[('sitemap_analysis', 'Sitemap Analysis'), ('seo_issues', 'SEO Issues Analysis'), ('full_report', 'Full Report'), ('general', 'General Question')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, help_text='Domain being analyzed (optional for general questions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name_plural': 'AI Conversations',
                'db_table': 'seo_ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('analysis', 'Analysis Result'), ('suggestion', 'Suggestion'), ('error', 'Error')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Message text content')),
                ('structured_data', models.JSONField(blank=True, help_text='Structured data like analysis results, suggestions', null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='seo_analyzer.aiconversation')),
            ],
            options={
                'verbose_name_plural': 'AI Messages',
                'db_table': 'seo_ai_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['domain', '-updated_at'], name='seo_ai_conv_domain__bfde32_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['created_by', '-updated_at'], name='seo_ai_conv_created_ca35a1_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['conversation_type'], name='seo_ai_conv_convers_904bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='seo_ai_mess_convers_28c92e_idx'),
        ),
    ]
