# Generated by Django 5.1.3 on 2026-02-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0027_ai_conversation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='sitemap_ai_enabled',
            field=models.BooleanField(default=True, help_text='Include in Sitemap AI analysis target list'),
        ),
    ]
