# Generated by Django 5.1.3 on 2026-02-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0028_add_sitemap_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemapentry',
            name='ai_analysis_enabled',
            field=models.BooleanField(default=True, help_text='Include in AI analysis'),
        ),
    ]
