# Generated by Django 5.1.3 on 2026-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0029_add_ai_analysis_enabled_to_sitemap_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoissue',
            name='ai_fix_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='ai_fix_explanation',
            field=models.TextField(blank=True, help_text='AI explanation for the fix', null=True),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='ai_fix_generated',
            field=models.BooleanField(default=False, help_text='Whether an AI fix was generated'),
        ),
        migrations.AddField(
            model_name='seoissue',
            name='ai_fix_generated_at',
            field=models.DateTimeField(blank=True, help_text='When AI fix was generated', null=True),
        ),
    ]
