# Generated by Django 5.1.3 on 2026-02-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0030_add_ai_fix_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFixHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(db_index=True, help_text='이슈 유형', max_length=100)),
                ('original_value', models.TextField(blank=True, help_text='수정 전 값', null=True)),
                ('fixed_value', models.TextField(help_text='AI가 제안한 수정 값')),
                ('ai_explanation', models.TextField(help_text='AI가 이 수정을 제안한 이유')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI 신뢰도 (0-1)')),
                ('ai_model', models.CharField(default='claude-sonnet-4-20250514', help_text='사용된 AI 모델', max_length=100)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='수정 시점의 SEO 데이터 스냅샷 (Search Console, 키워드 등)')),
                ('fix_status', models.CharField(choices=[('applied', '적용됨'), ('deployed', '배포됨'), ('verified', '검증됨'), ('reverted', '되돌림'), ('superseded', '대체됨'), ('failed', '실패')], db_index=True, default='applied', max_length=20)),
                ('effectiveness', models.CharField(choices=[('unknown', '알 수 없음'), ('effective', '효과적'), ('partial', '부분적'), ('ineffective', '비효과적'), ('negative', '부정적')], default='unknown', help_text='수정의 효과성', max_length=20)),
                ('effectiveness_evaluated_at', models.DateTimeField(blank=True, help_text='효과성 평가 시점', null=True)),
                ('issue_recurred', models.BooleanField(default=False, help_text='동일 이슈가 재발했는지')),
                ('recurrence_detected_at', models.DateTimeField(blank=True, help_text='재발 감지 시점', null=True)),
                ('recurrence_count', models.IntegerField(default=0, help_text='재발 횟수')),
                ('pre_fix_metrics', models.JSONField(blank=True, default=dict, help_text='수정 전 SEO 지표 (CTR, 순위 등)')),
                ('post_fix_metrics', models.JSONField(blank=True, default=dict, help_text='수정 후 SEO 지표')),
                ('deployed_to_git', models.BooleanField(default=False)),
                ('deployment_commit_hash', models.CharField(blank=True, max_length=40, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(blank=True, help_text='원본 이슈 (삭제되어도 이력은 유지)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fix_history', to='seo_analyzer.seoissue')),
                ('page', models.ForeignKey(help_text='수정이 적용된 페이지', on_delete=django.db.models.deletion.CASCADE, related_name='ai_fix_history', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name': 'AI Fix History',
                'verbose_name_plural': 'AI Fix Histories',
                'db_table': 'ai_fix_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'issue_type'], name='ai_fix_hist_page_id_3484a5_idx'), models.Index(fields=['page', 'created_at'], name='ai_fix_hist_page_id_926092_idx'), models.Index(fields=['issue_type', 'effectiveness'], name='ai_fix_hist_issue_t_af3206_idx'), models.Index(fields=['fix_status'], name='ai_fix_hist_fix_sta_135ed3_idx')],
            },
        ),
    ]
