# Generated by Django 5.1.3 on 2026-02-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0031_add_ai_fix_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='워크스페이스 이름', max_length=100)),
                ('description', models.TextField(blank=True, help_text='워크스페이스 설명', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='기본 워크스페이스 여부 (로그인 시 자동 로드)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opened_at', models.DateTimeField(blank=True, help_text='마지막 열람 시간', null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='워크스페이스 소유자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'seo_workspaces',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='커스텀 탭 이름 (비어있으면 도메인명 사용)', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='탭 순서')),
                ('is_active', models.BooleanField(default=False, help_text='현재 활성 탭')),
                ('viewport', models.JSONField(blank=True, default=dict, help_text='뷰포트 상태 {x, y, zoom}')),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='탭별 설정 {filterMode, layoutDirection, showHiddenNodes, ...}')),
                ('custom_positions', models.JSONField(blank=True, default=dict, help_text='커스텀 노드 위치 {nodeId: {x, y}, ...}')),
                ('has_unsaved_changes', models.BooleanField(default=False, help_text='미저장 변경사항 존재 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='표시할 도메인', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_tabs', to='seo_analyzer.domain')),
                ('workspace', models.ForeignKey(help_text='소속 워크스페이스', on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='seo_analyzer.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Tab',
                'verbose_name_plural': 'Workspace Tabs',
                'db_table': 'seo_workspace_tabs',
                'ordering': ['workspace', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', '-updated_at'], name='seo_workspa_owner_i_2ea1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner', 'is_default'], name='seo_workspa_owner_i_1552c1_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacetab',
            index=models.Index(fields=['workspace', 'order'], name='seo_workspa_workspa_e3e1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacetab',
            index=models.Index(fields=['workspace', 'is_active'], name='seo_workspa_workspa_b8a6f8_idx'),
        ),
    ]
