# Generated by Django 5.1.3 on 2026-02-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0032_add_workspace_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='탭 이름 (main, 2, 3, ...)', max_length=100)),
                ('is_main', models.BooleanField(default=False, help_text='메인 탭 여부 (메인 탭은 읽기 전용)')),
                ('order', models.PositiveIntegerField(default=0, help_text='탭 순서')),
                ('is_active', models.BooleanField(default=False, help_text='현재 활성 탭')),
                ('viewport', models.JSONField(blank=True, default=dict, help_text='뷰포트 상태 {x, y, zoom}')),
                ('custom_positions', models.JSONField(blank=True, default=dict, help_text='커스텀 노드 위치 {pageId: {x, y}, ...}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(help_text='소속 도메인', on_delete=django.db.models.deletion.CASCADE, related_name='canvas_tabs', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name': 'Canvas Tab',
                'verbose_name_plural': 'Canvas Tabs',
                'db_table': 'seo_canvas_tabs',
                'ordering': ['domain', 'order'],
                'indexes': [models.Index(fields=['domain', 'order'], name='seo_canvas__domain__81f30a_idx'), models.Index(fields=['domain', 'is_active'], name='seo_canvas__domain__f2016a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('domain',), name='unique_main_tab_per_domain')],
            },
        ),
    ]
