# Generated by Django 5.1.3 on 2026-02-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0033_add_canvas_tab_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('event', 'Event')], default='manual', max_length=20)),
                ('suggestions_count', models.IntegerField(default=0)),
                ('insights_count', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_runs', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name': 'AI Analysis Run',
                'verbose_name_plural': 'AI Analysis Runs',
                'db_table': 'ai_analysis_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('pages_synced', models.IntegerField(default=0)),
                ('embeddings_updated', models.IntegerField(default=0)),
                ('total_fixes_learned', models.IntegerField(default=0)),
                ('effective_fixes_count', models.IntegerField(default=0)),
                ('learning_quality_score', models.FloatField(default=0.0)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_learning_state', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name': 'AI Learning State',
                'verbose_name_plural': 'AI Learning States',
                'db_table': 'ai_learning_state',
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('title', 'Title Optimization'), ('description', 'Meta Description'), ('content', 'Content Improvement'), ('structure', 'Site Structure'), ('performance', 'Performance'), ('keyword', 'Keyword Strategy'), ('internal_link', 'Internal Linking'), ('priority_action', 'Priority Action'), ('quick_win', 'Quick Win'), ('general', 'General')], default='general', max_length=30)),
                ('priority', models.IntegerField(default=2)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('expected_impact', models.CharField(blank=True, max_length=500, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('is_auto_applicable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='seo_analyzer.aianalysisrun')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='seo_analyzer.domain')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='seo_analyzer.page')),
            ],
            options={
                'verbose_name': 'AI Suggestion',
                'verbose_name_plural': 'AI Suggestions',
                'db_table': 'ai_suggestions',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected'), ('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('incorrect', 'Incorrect')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='seo_analyzer.aisuggestion')),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedback',
                'db_table': 'ai_feedback',
            },
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['domain', 'status'], name='ai_suggesti_domain__da4c76_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['priority', '-created_at'], name='ai_suggesti_priorit_d1c4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='aisuggestion',
            index=models.Index(fields=['suggestion_type'], name='ai_suggesti_suggest_4e1e65_idx'),
        ),
    ]
