# Generated by Django 5.1.3 on 2026-02-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0034_ai_learning_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_snapshots', to='seo_analyzer.domain')),
            ],
            options={
                'verbose_name': 'Daily Traffic Snapshot',
                'verbose_name_plural': 'Daily Traffic Snapshots',
                'db_table': 'daily_traffic_snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['domain', '-date'], name='daily_traff_domain__82866e_idx')],
                'unique_together': {('domain', 'date')},
            },
        ),
    ]
