# Generated by Django 5.1.3 on 2026-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0035_daily_traffic_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='full_scan_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='gsc_sync_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_full_scan_at',
            field=models.DateTimeField(blank=True, help_text='Last full SEO scan timestamp', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_gsc_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last GSC sync timestamp', null=True),
        ),
    ]
