# Generated by Django 5.1.3 on 2026-02-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_analyzer', '0036_sync_status_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestion',
            name='baseline_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='추적 시작 시점의 기준 메트릭 스냅샷'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='effectiveness_score',
            field=models.FloatField(blank=True, help_text='AI가 평가한 효과성 점수 (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='final_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='추적 종료 시점의 최종 메트릭'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='impact_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI 효과 분석 결과'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='tracking_days',
            field=models.IntegerField(default=0, help_text='실제 추적된 일수'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='tracking_ended_at',
            field=models.DateTimeField(blank=True, help_text='추적 종료 시간', null=True),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='tracking_started_at',
            field=models.DateTimeField(blank=True, help_text='추적 시작 시간', null=True),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('tracking', 'Tracking'), ('tracked', 'Track Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SuggestionEffectivenessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('weekly', 'Weekly Analysis'), ('milestone', 'Milestone Analysis'), ('final', 'Final Analysis'), ('manual', 'Manual Analysis')], max_length=20)),
                ('days_since_applied', models.IntegerField(help_text='적용 후 경과 일수')),
                ('baseline_metrics', models.JSONField(default=dict, help_text='기준 메트릭 스냅샷')),
                ('current_metrics', models.JSONField(default=dict, help_text='현재 메트릭 스냅샷')),
                ('changes', models.JSONField(default=dict, help_text='메트릭 변화량 및 변화율')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Claude AI 분석 결과')),
                ('effectiveness_score', models.FloatField(blank=True, help_text='효과성 점수 (0-100)', null=True)),
                ('trend_direction', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('volatile', 'Volatile')], help_text='전체 트렌드 방향', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_logs', to='seo_analyzer.aisuggestion')),
            ],
            options={
                'verbose_name': 'Suggestion Effectiveness Log',
                'verbose_name_plural': 'Suggestion Effectiveness Logs',
                'db_table': 'suggestion_effectiveness_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['suggestion', '-created_at'], name='suggestion__suggest_6d53dd_idx'), models.Index(fields=['analysis_type'], name='suggestion__analysi_2ead4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestionTrackingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('day_number', models.IntegerField(default=1, help_text='추적 시작 후 N일차')),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(blank=True, help_text='CTR 퍼센트 (예: 5.2 = 5.2%)', null=True)),
                ('avg_position', models.FloatField(blank=True, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('keywords_count', models.IntegerField(default=0)),
                ('top_keywords', models.JSONField(blank=True, default=list, help_text='상위 키워드 목록 [{"keyword": "...", "impressions": N, "clicks": N}]')),
                ('impressions_change', models.IntegerField(default=0, help_text='기준 대비 노출수 변화량')),
                ('clicks_change', models.IntegerField(default=0, help_text='기준 대비 클릭수 변화량')),
                ('ctr_change', models.FloatField(blank=True, help_text='기준 대비 CTR 변화 (퍼센트 포인트)', null=True)),
                ('position_change', models.FloatField(blank=True, help_text='기준 대비 순위 변화 (음수=순위 상승)', null=True)),
                ('seo_score_change', models.FloatField(blank=True, help_text='기준 대비 SEO 점수 변화', null=True)),
                ('impressions_change_percent', models.FloatField(blank=True, help_text='기준 대비 노출수 변화율 (%)', null=True)),
                ('clicks_change_percent', models.FloatField(blank=True, help_text='기준 대비 클릭수 변화율 (%)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_snapshots', to='seo_analyzer.aisuggestion')),
            ],
            options={
                'verbose_name': 'Suggestion Tracking Snapshot',
                'verbose_name_plural': 'Suggestion Tracking Snapshots',
                'db_table': 'suggestion_tracking_snapshots',
                'ordering': ['suggestion', 'day_number'],
                'indexes': [models.Index(fields=['suggestion', 'date'], name='suggestion__suggest_16ae8a_idx'), models.Index(fields=['date'], name='suggestion__date_4cd348_idx')],
                'unique_together': {('suggestion', 'date')},
            },
        ),
    ]
